DSR_AUTOMATION/DSR_APP/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.upload_file, name='upload-page'),


    path('validation', views.upload_validation, name='upload-validation'),
    path('comparison/<str:instance>/', views.comparison_view, name='comparison-function'),

    path('processdata/<str:instance>/', views.process_data, name='process-data'),
    # path('addsheets/<str:instance>/', views.add_sheets, name='add-sheets'),
    path('generated/<str:instance>/', views.render_processed_data, name='generated-page'),
    path('download/<str:instance>/', views.download_excel, name='download-excel'),
    # path('edit-item-code/<int:row_id>/<int:file_id>/', views.edit_item_code, name='edit-item-code'),
    # path('edit-bp-code/<int:row_id>/<int:file_id>/', views.edit_bp_code, name='edit-bp-code'),
    path('edit-field/<str:field_name>/<int:row_id>/<int:file_id>/', views.edit_field, name='edit_field'),


    # path('validate', views.validatedsr, name='validate-dsr'),
    path('displaydsr/<str:doc_date>/<str:doc_remarks>/<str:database_type>/', views.displayuploadeddsr, name='display-dsr'),
    # path('detailed/<str:doc_date>/<str:doc_remarks>/<str:database_type>/', views.detaileddsr, name='display-detailed-dsr'),

    path('data/', views.show_data, name='data'),
    path('delete/<str:instance>/', views.delete_data, name='delete-data'),

    path('delete-selected/', views.delete_selected, name='delete-selected'),

    # path('generated/<str:batch_id>/', views.generated_page, name='generated-page'),
    # path('delete/<str:batch_id>/', views.delete_data, name='delete-data'),

    path('fetch-remarks/', views.fetch_remarks, name='fetch-remarks'),

    path('input-info/<str:chain>/<str:original_name>/<str:database>/', views.input_info, name="input-info"),


    # path('validate/<str:instance>/', views.validate_dsr, name='validate-dsr'),
]

DSR_AUTOMATION/DSR_AUTOMATION/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DSR_APP.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DSR_AUTOMATION/DSR_APP/models.py
from django.db import models


class DSR(models.Model):
    raw_file = models.FileField(upload_to='uploads/')
    date_of_generation = models.DateTimeField(auto_now_add=True)
    remarks = models.CharField(max_length=500)
    original_name = models.CharField(max_length=255, null=True, blank=True)
    special_remarks = models.CharField(max_length=500, null=True, blank=True)
    total_qty_sold = models.IntegerField(default=0)
    total_amount_template = models.FloatField(default=0.0)
    total_amount_raw = models.FloatField(default=0.0)

    uploader = models.CharField(max_length=200)
    extracted_data = models.JSONField(null=True)
    instance = models.CharField(max_length=100)
    chain = models.CharField(max_length=100)
    database = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.original_name

    class Meta:
        ordering = ['-date_of_generation']

class Validation(models.Model):
    generated_file = models.FileField(upload_to='validation/')
    date_of_comparison = models.DateTimeField(auto_now_add=True)
    original_name = models.CharField(max_length=255, null=True, blank=True)
    data_from_generated_file = models.JSONField(null=True)
    instance = models.CharField(max_length=100, null=True, blank=True)


    def __str__(self):
        return self.original_name

    class Meta:
        ordering = ['-date_of_comparison']

DSR_AUTOMATION/DSR_APP/forms.py
from django import forms
from . models import DSR, Validation

class DSRFormInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class DSRForm(forms.FileField): #FileField
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", DSRFormInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        # Handle single or multiple files
        cleaned_files = []
        if isinstance(data, (list, tuple)):  # Handle multiple files
            for file_data in data:
                cleaned_files.append(super().clean(file_data, initial))
        else:  # Handle single file
            cleaned_files.append(super().clean(data, initial))
        return cleaned_files
    
    
class FileFieldForm(forms.Form):
    file_field = DSRForm()





class ValidationFormInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class ValidForm(forms.FileField): #FileField
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", ValidationFormInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        # Handle single or multiple files
        cleaned_files = []
        if isinstance(data, (list, tuple)):  # Handle multiple files
            for file_data in data:
                cleaned_files.append(super().clean(file_data, initial))
        else:  # Handle single file
            cleaned_files.append(super().clean(data, initial))
        return cleaned_files
    
    
class ValidationForm(forms.Form):
    file_field = ValidForm()

DSR_AUTOMATION/DSR_APP/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.db import connection
from .forms import FileFieldForm, ValidationForm
import traceback
from difflib import SequenceMatcher
import re
from .models import DSR, Validation
from collections import defaultdict

from django.shortcuts import get_object_or_404
import os
import re
from django.views.decorators.csrf import csrf_exempt
import logging
from DSR_APP.queries import fetch_item_code_results, fetch_bp_code_results
from DSR_APP.services.sap_query_conn import execute_query
from .mapping import chain_mapping, db_mapping
from django.http import JsonResponse
from dateutil.relativedelta import relativedelta
from datetime import datetime
from zipfile import ZipFile
from io import BytesIO
import pandas as pd
from decimal import Decimal
from django.db import transaction #For batch processing
import uuid  # For generating unique instance identifiers
# from .views2 import validate_dsr

bp_code_results = []
item_code_results = []
ALLOWED_FILE_EXTENSIONS = ['xls', 'xlsx', 'xlsm', 'csv', 'xlsb', 'xltx', 'xltm']

logger = logging.getLogger(__name__)


# #########QUERY TO FETCH BP CODES WITH BRANCH ID 
# def fetch_bp_code_results(chain, database):
#     """Fetch the BP Code results and store them in a global list."""
#     global bp_code_results

#     query = f"""
#         SELECT 
#             a."CardCode",
#             a."CardName",
#             a."AddID"
#         FROM OCRD a
#         LEFT JOIN CPN1 b ON b."BpCode" = a."CardCode"
#         INNER JOIN OCPN c ON c."CpnNo" = b."CpnNo" AND c."U_CType" = 'SKU' AND c."U_Chain" = '{chain}'
#         WHERE a."frozenFor" = 'N'
#     """

#     try:
#         # Execute the query and fetch results
#         bp_code_results = execute_query(query, database)
#     except Exception as e:
#         # Handle any errors gracefully and leave bp_code_results empty
#         bp_code_results = []

    
# #########QUERY TO FETCH ITEM CODES WITH PRICE
# def fetch_item_code_results(chain, database):
#     global item_code_results
#     query = f"""
#         SELECT 
#             b."ItemCode",
#             b."ItemName",
#             b."U_SKU",
#             d."Price",
#             b."U_BarCode"
#         FROM OCPN a
#         JOIN CPN2 b ON a."CpnNo" = b."CpnNo"
#         JOIN OITM c ON c."ItemCode" = b."ItemCode"
#         JOIN ITM1 d ON d."ItemCode" = c."ItemCode"
#         WHERE a."U_Chain" = '{chain}' 
#         AND d."PriceList" = 2 
#         AND b."U_SKU" IS NOT NULL
#         AND c."frozenFor" = 'N';
#     """

#     try:
#         item_code_results = execute_query(query, database)
#     except Exception as e:
#         item_code_results = []



def get_headers(chain):

    DATE = ['date', 'tran date', 'date sold', 'transaction start', 'transaction date']


    if chain in ['ALLHOME', 'FISHER']:
        QTY = ['qty sold', 'qty', 'qty/kilo', 'quantity', 'units sold ty']
        DATE = ['date', 'tran date', 'date sold', 'transaction start', 'transaction date']
        GROSS = ['net sales']
        STORECODE = ['branch']

    # elif chain == 'HWORKS':
    #     QTY = ['ttl sold']
    #     DATE = ['transaction date']
    #     GROSS = ['total amount', 'gross sales amt', 'sales amount', 'gross amount', 'gross sales', 'gross sales ty']

    elif chain == 'WDS':
        QTY = ['qty sold', 'qty', 'qty/kilo', 'quantity', 'units sold ty']
        DATE = ['transaction date']
        GROSS = ['total amount', 'gross sales amt', 'sales amount', 'gross amount', 'gross sales', 'gross sales ty']
        STORECODE = ['site code']

    else:
        QTY = ['qty sold', 'qty', 'qty/kilo', 'quantity', 'units sold ty']
        DATE = ['date', 'tran date', 'date sold', 'transaction start']
        GROSS = ['total amount', 'gross sales amt', 'sales amount', 'gross amount', 'gross sales', 'gross sales ty']
        STORECODE = ['site code', 'store code', 'branch code']

    return {
        'SKU': ['matcode', 'sku#', 'sku', 'sku number', 'sku code'],
        'BRANCH': ['store name', 'branch', 'site name', 'branch name', 'store description', 'vendor name'],
        'DATE': DATE,
        'DESC': ['description', 'item description', 'item name', 'sku description', 'product', 'product description'],
        'STORE_CODE': STORECODE,
        'QTY': QTY,
        'GROSS': GROSS,
        'BPCODE': ['bp code'],
        'ITEMCODE':['item code', 'item number']
    }


@csrf_exempt
def process_data(request, instance):
    """Process and extract data from the uploaded files, then save it to the database."""
    extracted_data = []  # Local variable to store extracted data.
    global item_code_results, bp_code_results

    def get_column_name(possible_names, df_columns):
        """
        Find the first matching column name from possible_names in df_columns (case-insensitive and whitespace-agnostic).
        """
        df_columns_normalized = {col.strip().lower(): col for col in df_columns}  # Normalize column names
        for name in possible_names:
            if name.strip().lower() in df_columns_normalized:
                return df_columns_normalized[name.strip().lower()]  # Return the original column name
        return None

    ###Dynamically check where the row starts for extracting the data
    def detect_header_row(df, chain):
        """
        Automatically detect the header row by scanning the first few rows for matching column names.
        """
        HEADERS = get_headers(chain)

        for i, row in df.iterrows():
            normalized_row = row.astype(str).str.strip().str.lower()
            if any(col_name.lower() in normalized_row.values for col_list in HEADERS.values() for col_name in col_list):
                print(f"Header row detected at index {i}")
                return i  # Return the row index
        return 0  # Default to the first row if no match is found

    # Fetch all files associated with the given instance
    files = DSR.objects.filter(instance=instance)
    print(f"Processing {len(files)} files for instance {instance}.")


    for file in files:

        # Add BP Code using store_name and chain ------------------------
        file_name = file.raw_file.name.lower().strip().replace(" ", "").replace("_", "")   # Remove spaces and lowercase the file name for comparison
        print(f"Processing file: {file_name}")


        # Determine the appropriate engine based on file extension
        if file_name.endswith('.xls'):
            engine = 'xlrd'  # For .xls files
        else:
            engine = 'openpyxl'  # For .xlsx files


        

        # Get file path
        file_path = file.raw_file.path  # Move file_path assignment here
        # Read the Excel file using the determined engine
        print(f"Reading file from path: {file_path}")
        df = pd.read_excel(file_path, engine=engine, header=None)
        
        database = ''
        for keyword, db_name in db_mapping.items():
            cleaned_keyword = keyword.replace(" ", "").lower()
            if cleaned_keyword in file_name:
                database = db_name


        # Ensure case-insensitive matching and remove spaces for both file name and dictionary keys
        chain = ''
        for keyword, chain_name in chain_mapping.items():
            cleaned_keyword = keyword.replace(" ", "").lower()
            if cleaned_keyword in file_name:
                chain = chain_name
        

        if database == 'EPC' and chain == 'SM':
            chain = 'SM HOMEWORLD'
        elif database == 'NBFI' and chain == 'SM':
            chain = 'SM DEPT. STORE'
        elif not chain:
            chain = None

        print(f"chain is: {chain} ")
                
        if chain and database != '':
            file.chain = chain
            file.database = database
            file.save()
            bp_code_results = fetch_bp_code_results(chain, database)
            item_code_results = fetch_item_code_results(chain, database)
            if item_code_results:
                print(f"Successful ka sa itemcodes")
            elif bp_code_results:
                print(f"Successful ka sa bpcodes")
            else:
                print(f"sad bobo ka")
                


        else:
            print(f"No valid chain found for file: {file.raw_file.name}")
            continue

        #-------------------------------------------------

        if file.chain and file.database != '':
            

            try:
                # Detect the header row dynamically
                print("Detecting header row...")
                header_row = detect_header_row(df, chain)
                HEADERS = get_headers(chain)

                df.columns = df.iloc[header_row].apply(str).str.strip()  # Set the detected header row as columns
                df = df.iloc[header_row + 1:]  # Skip the header row in the data

                # Check if the DATE column exists
                print("Checking for DATE column...")
                date_column = get_column_name(HEADERS['DATE'], df.columns)
                if not date_column:
                    print(f"File {file.raw_file.name} has no DATE column. Including all rows for processing.")

                gross_column = get_column_name(HEADERS['GROSS'], df.columns) #################################ABSOLUTE VALUE
                if not gross_column:
                    print(f"File {file.raw_file.name} has no Gross column. Including all rows for processing.")

                # Map columns dynamically for the remaining columns
                column_map = {}
                missing_headers = []  # List to store missing headers
                for key, col_list in HEADERS.items():
                    matched_col = get_column_name(col_list, df.columns)
                    if not matched_col:
                        # Only return an error for essential columns (e.g., SKU, QTY, GROSS)

DSR_AUTOMATION/DSR_APP/templates/app/comparison.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comparison Table</title>
</head>
<body>
    <h2>Comparison Data</h2>
    <table border="1">
        <thead>
            <tr>
                <th>BP CODE</th>
                <th>Quantity Sold</th>
                <th>Gross Sales</th>
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
                <tr>
                    <td>{{ row.BP_CODE }}</td>
                    <td>{{ row.Quantity_Sold }}</td>
                    <td>{{ row.Sales }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

DSR_AUTOMATION/DSR_APP/templates/app/detailed_dsr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DSR Detailed Result</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }
        th {
            background-color: #f4f4f4;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        tr:hover {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body>

<h1>DSR Detailed Result</h1>

{% if items %}
    <table>
        <thead>
            <tr>
                {% for header in headers %}
                    <th>{{ header }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in items %}
                <tr>
                    {% for key, value in row.items %}
                        <td>{{ value }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No data available for the selected date and remarks.</p>
{% endif %}

</body>
</html>

DSR_AUTOMATION/DSR_APP/templates/app/landing_page.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

        <H1>Welcome</H1>
        <form action = "{% url 'upload-page' %}">
            <button class ="btn-btn" type="submit">Generate DSR Template</button>
            
        </form>
    </body>
</html>

DSR_AUTOMATION/DSR_APP/templates/app/main.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <H1>Daily Sales Record Template Generator</H1>

    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

DSR_AUTOMATION/DSR_APP/templates/app/upload.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload Files</title>
    <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
    <style>
        /* Simple CSS for loading spinner */
        #loading {
            display: flex;
            position: fixed; /* Ensure the spinner covers the entire viewport */
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(255, 255, 255, 0.8);
            justify-content: center; /* Center horizontally */
            align-items: center;  /* Center vertically */
            z-index: 9999; /* Make sure it appears above all content */
        }
    
        .spinner {
            border: 4px solid #f3f3f3;
            border-top: 4px solid #3498db;
            border-radius: 50%;
            width: 50px;
            height: 50px;
            animation: spin 2s linear infinite;
        }
    
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
    
        /* Style the rest of the form */
        body {
            padding: 20px;
        }
    
        /* Error message styling */
        .error {
            color: red;
            font-size: 14px;
            display: none;
        }
    </style>
    
</head>
<body>
    <div>
        <a href="{% url 'data' %}" class="rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-xs cursor-pointer hover:bg-green-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Check Uploaded DSR</a>
    </div>
    <div style="margin: auto;" class="w-3xl rounded-md p-4 border border-gray-900/25">
        <form method="POST" enctype="multipart/form-data" id="uploadForm">
        {% csrf_token %}
        <div class="space-y-12">
          <div class="border-b border-gray-900/10 pb-12">
            <h1 class="text-base/7 font-semibold text-gray-900">DSR AUTOMATION</h1>
            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
              <div class="sm:col-span-3">
                <label for="first-name" class="block text-sm/6 text-gray-900 font-bold">Generated By:</label>
                <div class="mt-2">
                        <input type="text" name="uploader" value="" id="id_uploader" required class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                      </div>
                    </div>
                    <div class="sm:col-span-3">
                      <label for="first-name" class="block text-sm/6 text-gray-900 font-bold">Remarks:</label>
                      <div class="mt-2">
                        <input type="text" name="remarks"  value="" id="id_remarks" required class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                      </div>
                    </div>

                <div class="col-span-full">
                  <label for="cover-photo" class="block text-sm/6 text-gray-900 font-bold">Upload File</label>
                  <p class="mt-1 text-sm/6 text-gray-600">Requirements</p>
                  <li class="mt-1 text-sm/6 text-gray-600">The file name MUST include the Business Unit and chain (e.g., EPC ALLHOME or NBFI RDS).</li>
                  <li class="mt-1 text-sm/6 text-gray-600">Files should be in Excel format (e.g., 'xls', 'xlsx', 'xlsm', 'csv', 'xlsb', 'xltx', 'xltm').</li>
                  <li class="mt-1 text-sm/6 text-gray-600">Data should be contained in a single sheet only.</li>



                  <div id="drop-area" class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
                      <div class="text-center">
                          <svg class="mx-auto size-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" data-slot="icon">
                              <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 0 1 2.25-2.25h16.5A2.25 2.25 0 0 1 22.5 6v12a2.25 2.25 0 0 1-2.25 2.25H3.75A2.25 2.25 0 0 1 1.5 18V6ZM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0 0 21 18v-1.94l-2.69-2.689a1.5 1.5 0 0 0-2.12 0l-.88.879.97.97a.75.75 0 1 1-1.06 1.06l-5.16-5.159a1.5 1.5 0 0 0-2.12 0L3 16.061Zm10.125-7.81a1.125 1.125 0 1 1 2.25 0 1.125 1.125 0 0 1-2.25 0Z" clip-rule="evenodd" />
                          </svg>
                          <div class="mt-4 flex text-sm/6 text-gray-600">
                              <label hidden for="file-upload" class="relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 focus-within:outline-hidden hover:text-indigo-500">
                                  {{  form.as_p }}
                              </label>
                          </div>
                          <p class="pl-1">Drag and Drop files to upload</p>
                          <p class="text-xs/5 text-gray-600">Supported file types: <b>xls, xlsx, xlsm, csv, xlsb, xltx, xltm</b></p>
                      </div>
                  </div>
                  <div id="file-list" class="mt-4">
                      <h3 class="text-sm/6 text-gray-900 font-bold">Uploaded Files:</h3>
                      <div id="uploaded-files" class="list-disc pl-5 text-sm/6 text-gray-800 p-4">
                      </div>
                      <!-- <ul id="uploaded-files" class="list-disc pl-5 text-sm/6 text-gray-600"></ul> -->
                  </div>
              </div>
                </div>
              </div>
            </div>
          
            <div class="mt-6 flex items-center justify-end gap-x-6">
              <!-- <button type="button" class="text-sm/6 font-semibold text-gray-900">Cancel</button> -->
              <button type="submit" class="rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-xs cursor-pointer hover:bg-green-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Generate</button>
            </div>
        </form>
    </div>
      

















    <!-- Error message for invalid file types -->
    <div id="fileError" class="error">Please upload only .xls, .xlsx, .xlsm, or .csv files.</div>

    <!-- Loading spinner -->
    <div id="loading" >
        <div class="spinner"></div>
        <p>Generating Template...</p>
    </div>

    <script>
        // Function to validate file extensions
        function validateFiles(files) {
            const allowedExtensions = ['xls', 'xlsx', 'xlsm', 'csv'];
            for (let i = 0; i < files.length; i++) {
                const fileExtension = files[i].name.split('.').pop().toLowerCase();
                if (!allowedExtensions.includes(fileExtension)) {
                    return false; // Invalid file type
                }
            }
            return true; // All files are valid
        }

        // Show the loading spinner when the form is submitted
        document.getElementById('uploadForm').addEventListener('submit', function(event) {
            const files = document.getElementById('id_file_field').files;
            
            // Validate files before submitting the form
            if (!validateFiles(files)) {
                // Prevent form submission if invalid file
                event.preventDefault();
                
                // Show error message
                document.getElementById('fileError').style.display = 'block';
            } else {
                // Hide error message if files are valid
                document.getElementById('fileError').style.display = 'none';
                
                // Show the loading spinner
                document.getElementById('loading').style.display = 'flex';
            }
        });

        // Optionally, you can hide the spinner after the page is fully loaded
        window.addEventListener('load', function() {
            document.getElementById('loading').style.display = 'none';
        });



       
        

        const dropArea = document.getElementById('drop-area');
const fileInput = document.querySelector('input[type="file"]'); // Select the file input generated by Django
const uploadedFilesList = document.getElementById('uploaded-files'); // List to display uploaded files

// Prevent default drag behaviors
['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
    dropArea.addEventListener(eventName, preventDefaults, false);
    document.body.addEventListener(eventName, preventDefaults, false);
});

// Highlight the drop area when item is dragged over it
['dragenter', 'dragover'].forEach(eventName => {
    dropArea.addEventListener(eventName, highlight, false);
});

// Remove highlight when item is dragged away
['dragleave', 'drop'].forEach(eventName => {
    dropArea.addEventListener(eventName, unhighlight, false);
});

// Handle dropped files
dropArea.addEventListener('drop', handleDrop, false);

function preventDefaults(e) {
    e.preventDefault();
    e.stopPropagation();
}

function highlight() {
    dropArea.classList.add('bg-gray-200', 'border-blue-500'); // Add highlight styles
}

function unhighlight() {
    dropArea.classList.remove('bg-gray-200', 'border-blue-500'); // Remove highlight styles
}

function handleDrop(e) {
    const dt = e.dataTransfer;
    const files = dt.files;

    handleFiles(files);
}

function handleFiles(files) {
    // Update the file input with the dropped files
    const dataTransfer = new DataTransfer();
    for (let i = 0; i < files.length; i++) {
        dataTransfer.items.add(files[i]);
        addFileToList(files[i].name); // Add file name to the list
    }
    fileInput.files = dataTransfer.files; // Update the file input with the dropped files

    // Optionally, you can upload the files here
    for (let i = 0; i < files.length; i++) {
        uploadFile(files[i]);
    }
}

function addFileToList(fileName) {
    const listItem = document.createElement('li');
    listItem.textContent = fileName;
    listItem.classList.add('bg-gray-100', 'p-2', 'rounded', 'mb-1'); // Add Tailwind CSS classes
    uploadedFilesList.appendChild(listItem);
}

function uploadFile(file) {
    const formData = new FormData();
    formData.append('file', file);

    // Example of an AJAX request to upload the file
    fetch('/upload', {
        method: 'POST',
        body: formData
    })
    .then(response => response.json())
    .then(data => {
        console.log('Success:', data);
    })
    .catch((error) => {
        console.error('Error:', error);
    });
}


        
    </script>
</body>
</html>